### ISSUE TITLE
Improved pia_communicator

### ISSUE THREAD

**Issue by jblang** [tebl/RC6502-Apple-1-Replica#1]
I have written an improved version of the pia_communicator firmware since I found the original firmware to be painfully slow, especially when loading large hex files into the monitor. It is available here: https://github.com/jblang/pia_communicator.

**Comment by tebl** [comment]
Thank you, I added a notice about it to the README for the relevant module. Have yet to do much testing on it, but hopefully I'll get to it in... was tempted to say "due time", but guessing we're past that at this point :-)
