### ISSUE TITLE
Which versions of 6502 are compatible with SBC version?

### ISSUE THREAD

**Issue by natevw** [tebl/RC6502-Apple-1-Replica#18]
Hello, thank you for this design! Looks fun, I have some PCBs on their way and hoping to build one maybe with a Rapberry Pi Pico eventually!

I am trying to source the right 6502 processor without spending too much. The BOM says "UM6502 or SY6502" implying this needs an NMOS version of the 6502? These are older and more expensive afaict. I also read at https://github.com/tebl/RC6502-Apple-1-Replica/issues/2#issuecomment-478630350:

> it does not appear to work with a Rockwell R6502AP (or I have a bad one.)

Which I think is NMOS but at least a different (maximum? must be exact?) clock speed of 2MHz instead of the usual 1MHz.

But I also read on https://hvetebolle.blogspot.com/2017/06/rc6502-montering-og-feilsking.html (translated):

> [3.3k resistor] recommended when using 65c02 processors from Western Design […] The card works with the far cheaper and far more up-to-date versions of the 6502 processor, so is happy so far.

That sounds like the newer cheap CMOS ones? Would a W65C02S6TPG-14 work in the SBC version current revision? [Although maybe not much cheaper new than vintage eBay parts anyway…]

**Comment by tebl** [comment]
The W65c02 was more done from a theoretical standpoint after reading a
Western Designs document on substituting them, but have not had much luck
getting them to work. W65C21N should be paired with it, S-variant
definitely won't work.

R6502AP I think should be comparable to UM and SY branded 6502, I at least
remember using one at some point.

søn. 11. apr. 2021, 06:38 skrev Nathan Vander Wilt ***@***.***
