### ISSUE TITLE
RC6502 VDU Color Amplifier - J4 OSC_EN Not connected?

### ISSUE THREAD

**Issue by StormTrooper** [tebl/RC6502-Apple-1-Replica#32]
On the schematic for the RC6502 VDU Color Amplifier, J4 (OSC_EN) is not connected to anything? Is this for a future feature or can it be removed?

**Comment by tebl** [comment]
I assume you already found this out, but for posterity and those that might be looking for this answer at some point... J4 is a female pin header that matches up to some pin headers on the VDU board itself, it's existence is just a mechanical way of ensuring that these pin headers don't have a jumper on them.
